## change according to your env and create kubernetes/secret.yaml file
apiVersion: v1
kind: Secret
metadata:   
  name: db-credentials
  namespace: vote-app
type: Opaque
data: 
  DB_USER: devopsZGV2b3BzCg==  ## echo -n 'devops' | base64
  DB_PASSWORD: UGFzc0AxMjM0Cg== ## echo -n 'Pass@1234' | base64
  DB_NAME: dm90aW5nX2FwcAo=  ## echo -n 'voting_app' | base64
  DB_ROOT_PASSWORD: Um9vdEAxMjM0Cg== ## echo -n 'Root@1234' | base64