## change according to your env and create kubernetes/secret.yaml file
apiVersion: v1
kind: Secret
metadata:   
  name: db-credentials
  namespace: vote-app
type: Opaque
data: 
  DB_USER: ZGV2b3Bz  ## echo -n 'username' | base64
  DB_PASSWORD: UGFzc0AxMjM0 ## echo -n 'secure_password' | base64
  DB_NAME: dm90aW5nX2FwcA==  ## echo -n 'voting_app' | base64
  DB_ROOT_PASSWORD: Um9vdEAxMjM0 ## echo -n 'root_passwod' | base64
