apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: vote-app-backend
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 5000
    targetPort: 5000
    #nodePort: 30001
  type: ClusterIP