apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: vote-app
spec:
  selector:
    app: vote-app-frontend
  ports:
  - name: frontend service-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
## if you are using LoadBalancer type service then uncomment below lines and comment NodePort type service
#  type: LoadBalancer