apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app-frontend
  name: frontend-vote-app-deployment
  namespace: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app-frontend
  template:
    metadata:
      labels:
        app: vote-app-frontend
    spec:
      containers:
      - image: kishor95/vote-app-frontend:11
        imagePullPolicy: IfNotPresent
        name: frontend-vote-app
        ports:
        - containerPort: 80
          protocol: TCP
