---
## Service for MySQL Deployment
apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment-service
  namespace: vote-app
spec:
  selector:
    app: mysql-deployment
  ports:
    - name: mysql-port 
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP