## Configuration For Persistent Volume (Optional, depending on your cluster setup)
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: vote-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  spec:
  hostPath:
    path: /mnt/data/mysql
  storageClassName: ""
  claimRef:
    namespace: vote-app
    name: mysql-pvc